//
//  CTAStyleKit.swift
//  CuriosText
//
//  Created by Emiaostein on 1/13/16.
//  Copyright (c) 2016 com.botai. All rights reserved.
//
//  Generated by PaintCode (www.paintcodeapp.com)
//



import UIKit

public class CTAStyleKit : NSObject {

    //// Cache

    private struct Cache {
        static let normalColor: UIColor = UIColor(red: 0.633, green: 0.633, blue: 0.633, alpha: 1.000)
        static let selectedColor: UIColor = UIColor(red: 1.000, green: 0.000, blue: 0.000, alpha: 1.000)
        static let red0: UIColor = UIColor(red: 0.592, green: 0.067, blue: 0.349, alpha: 1.000)
        static let red1: UIColor = UIColor(red: 0.596, green: 0.000, blue: 0.000, alpha: 1.000)
        static let red2: UIColor = UIColor(red: 0.792, green: 0.000, blue: 0.000, alpha: 1.000)
        static let red3: UIColor = UIColor(red: 0.898, green: 0.000, blue: 0.000, alpha: 1.000)
        static let red4: UIColor = UIColor(red: 0.898, green: 0.000, blue: 0.000, alpha: 1.000)
        static let red5: UIColor = UIColor(red: 0.898, green: 0.000, blue: 0.306, alpha: 1.000)
        static let red6: UIColor = UIColor(red: 0.788, green: 0.000, blue: 0.082, alpha: 1.000)
        static let red7: UIColor = UIColor(red: 1.000, green: 0.105, blue: 0.309, alpha: 1.000)
        static let red8: UIColor = UIColor(red: 1.000, green: 0.563, blue: 0.663, alpha: 1.000)
        static let yellow0: UIColor = UIColor(red: 0.898, green: 0.725, blue: 0.318, alpha: 1.000)
        static let yellow1: UIColor = UIColor(red: 0.745, green: 0.545, blue: 0.102, alpha: 1.000)
        static let yellow2: UIColor = UIColor(red: 0.698, green: 0.745, blue: 0.000, alpha: 1.000)
        static let yellow3: UIColor = UIColor(red: 0.875, green: 0.898, blue: 0.000, alpha: 1.000)
        static let yellow4: UIColor = UIColor(red: 0.878, green: 0.898, blue: 0.322, alpha: 1.000)
        static let yellow5: UIColor = UIColor(red: 0.631, green: 0.898, blue: 0.000, alpha: 1.000)
        static let yellow6: UIColor = UIColor(red: 0.306, green: 0.898, blue: 0.000, alpha: 1.000)
        static let yellow7: UIColor = UIColor(red: 0.958, green: 1.000, blue: 0.471, alpha: 1.000)
        static let yellow8: UIColor = UIColor(red: 0.985, green: 1.000, blue: 0.811, alpha: 1.000)
        static let blue0: UIColor = UIColor(red: 0.187, green: 0.006, blue: 0.507, alpha: 1.000)
        static let blue1: UIColor = UIColor(red: 0.184, green: 0.006, blue: 0.500, alpha: 1.000)
        static let blue2: UIColor = UIColor(red: 0.263, green: 0.000, blue: 0.729, alpha: 1.000)
        static let blue3: UIColor = UIColor(red: 0.086, green: 0.102, blue: 0.545, alpha: 1.000)
        static let blue4: UIColor = UIColor(red: 0.247, green: 0.000, blue: 0.898, alpha: 1.000)
        static let blue5: UIColor = UIColor(red: 0.161, green: 0.000, blue: 0.729, alpha: 1.000)
        static let blue6: UIColor = UIColor(red: 0.000, green: 0.322, blue: 0.729, alpha: 1.000)
        static let blue7: UIColor = UIColor(red: 0.075, green: 0.514, blue: 0.898, alpha: 1.000)
        static let blue8: UIColor = UIColor(red: 0.212, green: 0.722, blue: 0.898, alpha: 1.000)
        static let green0: UIColor = UIColor(red: 0.000, green: 0.380, blue: 0.188, alpha: 1.000)
        static let green1: UIColor = UIColor(red: 0.000, green: 0.576, blue: 0.043, alpha: 1.000)
        static let green2: UIColor = UIColor(red: 0.000, green: 0.757, blue: 0.373, alpha: 1.000)
        static let green3: UIColor = UIColor(red: 0.000, green: 0.761, blue: 0.055, alpha: 1.000)
        static let green4: UIColor = UIColor(red: 0.000, green: 0.898, blue: 0.098, alpha: 1.000)
        static let green5: UIColor = UIColor(red: 0.000, green: 0.557, blue: 0.549, alpha: 1.000)
        static let green6: UIColor = UIColor(red: 0.000, green: 0.898, blue: 0.549, alpha: 1.000)
        static let green7: UIColor = UIColor(red: 0.235, green: 0.573, blue: 0.229, alpha: 1.000)
        static let green8: UIColor = UIColor(red: 0.492, green: 0.800, blue: 0.487, alpha: 1.000)
        static let orange0: UIColor = UIColor(red: 0.792, green: 0.514, blue: 0.000, alpha: 1.000)
        static let orange1: UIColor = UIColor(red: 0.898, green: 0.583, blue: 0.000, alpha: 1.000)
        static let orange2: UIColor = UIColor(red: 0.898, green: 0.583, blue: 0.000, alpha: 1.000)
        static let orange3: UIColor = UIColor(red: 0.898, green: 0.583, blue: 0.000, alpha: 1.000)
        static let orange4: UIColor = UIColor(red: 1.000, green: 0.732, blue: 0.236, alpha: 1.000)
        static let orange5: UIColor = UIColor(red: 1.000, green: 0.792, blue: 0.406, alpha: 1.000)
        static let orange6: UIColor = UIColor(red: 1.000, green: 0.816, blue: 0.476, alpha: 1.000)
        static let orange7: UIColor = UIColor(red: 1.000, green: 0.890, blue: 0.686, alpha: 1.000)
        static let orange8: UIColor = UIColor(red: 1.000, green: 0.891, blue: 0.690, alpha: 1.000)
        static let indigo0: UIColor = UIColor(red: 0.635, green: 1.000, blue: 1.000, alpha: 1.000)
        static let indigo1: UIColor = UIColor(red: 0.436, green: 1.000, blue: 1.000, alpha: 1.000)
        static let indigo2: UIColor = UIColor(red: 0.388, green: 0.898, blue: 0.898, alpha: 1.000)
        static let indigo3: UIColor = UIColor(red: 0.000, green: 0.898, blue: 0.898, alpha: 1.000)
        static let indigo4: UIColor = UIColor(red: 0.000, green: 0.898, blue: 0.898, alpha: 1.000)
        static let indigo5: UIColor = UIColor(red: 0.000, green: 0.741, blue: 0.733, alpha: 1.000)
        static let indigo6: UIColor = UIColor(red: 0.000, green: 0.725, blue: 0.898, alpha: 1.000)
        static let indigo7: UIColor = UIColor(red: 0.000, green: 0.655, blue: 0.808, alpha: 1.000)
        static let indigo8: UIColor = UIColor(red: 0.000, green: 0.541, blue: 0.729, alpha: 1.000)
        static let purple0: UIColor = UIColor(red: 0.422, green: 0.196, blue: 0.490, alpha: 1.000)
        static let purple1: UIColor = UIColor(red: 0.420, green: 0.184, blue: 0.490, alpha: 1.000)
        static let purple2: UIColor = UIColor(red: 0.590, green: 0.424, blue: 0.640, alpha: 1.000)
        static let purple3: UIColor = UIColor(red: 0.656, green: 0.516, blue: 0.698, alpha: 1.000)
        static let purple4: UIColor = UIColor(red: 0.621, green: 0.467, blue: 0.667, alpha: 1.000)
        static let purple5: UIColor = UIColor(red: 0.651, green: 0.286, blue: 0.761, alpha: 1.000)
        static let purple6: UIColor = UIColor(red: 0.377, green: 0.000, blue: 0.490, alpha: 1.000)
        static let purple7: UIColor = UIColor(red: 0.527, green: 0.231, blue: 0.616, alpha: 1.000)
        static let purple8: UIColor = UIColor(red: 0.718, green: 0.603, blue: 0.752, alpha: 1.000)
        static let black0: UIColor = UIColor(red: 0.153, green: 0.153, blue: 0.153, alpha: 1.000)
        static let black1: UIColor = UIColor(red: 0.216, green: 0.216, blue: 0.216, alpha: 1.000)
        static let black2: UIColor = UIColor(red: 0.000, green: 0.000, blue: 0.000, alpha: 1.000)
        static let black3: UIColor = UIColor(red: 0.149, green: 0.149, blue: 0.149, alpha: 1.000)
        static let black4: UIColor = UIColor(red: 0.294, green: 0.294, blue: 0.294, alpha: 1.000)
        static let black5: UIColor = UIColor(red: 0.447, green: 0.447, blue: 0.447, alpha: 1.000)
        static let black6: UIColor = UIColor(red: 0.600, green: 0.600, blue: 0.600, alpha: 1.000)
        static let black7: UIColor = UIColor(red: 0.749, green: 0.749, blue: 0.749, alpha: 1.000)
        static let black8: UIColor = UIColor(red: 1.000, green: 1.000, blue: 1.000, alpha: 1.000)
        static let salamander0: UIColor = UIColor(red: 0.871, green: 0.804, blue: 0.000, alpha: 1.000)
        static let salamander1: UIColor = UIColor(red: 0.898, green: 0.424, blue: 0.000, alpha: 1.000)
        static let salamander2: UIColor = UIColor(red: 0.898, green: 0.616, blue: 0.000, alpha: 1.000)
        static let salamander3: UIColor = UIColor(red: 0.549, green: 0.376, blue: 0.094, alpha: 1.000)
        static let salamander4: UIColor = UIColor(red: 0.878, green: 0.000, blue: 0.416, alpha: 1.000)
        static let salamander5: UIColor = UIColor(red: 0.784, green: 0.859, blue: 0.745, alpha: 1.000)
        static let salamander6: UIColor = UIColor(red: 0.325, green: 0.722, blue: 0.227, alpha: 1.000)
        static let salamander7: UIColor = UIColor(red: 0.176, green: 0.122, blue: 0.471, alpha: 1.000)
        static let salamander8: UIColor = UIColor(red: 0.000, green: 0.655, blue: 0.796, alpha: 1.000)
        static let intoDreams0: UIColor = UIColor(red: 0.816, green: 0.682, blue: 0.784, alpha: 1.000)
        static let intoDreams1: UIColor = UIColor(red: 0.604, green: 0.000, blue: 0.518, alpha: 1.000)
        static let intoDreams2: UIColor = UIColor(red: 0.741, green: 0.353, blue: 0.565, alpha: 1.000)
        static let intoDreams3: UIColor = UIColor(red: 0.835, green: 0.000, blue: 0.000, alpha: 1.000)
        static let intoDreams4: UIColor = UIColor(red: 0.627, green: 0.102, blue: 0.012, alpha: 1.000)
        static let intoDreams5: UIColor = UIColor(red: 0.329, green: 0.298, blue: 0.314, alpha: 1.000)
        static let intoDreams6: UIColor = UIColor(red: 0.169, green: 0.129, blue: 0.153, alpha: 1.000)
        static let intoDreams7: UIColor = UIColor(red: 0.361, green: 0.588, blue: 0.220, alpha: 1.000)
        static let intoDreams8: UIColor = UIColor(red: 0.000, green: 0.255, blue: 0.192, alpha: 1.000)
        static let cynicide0: UIColor = UIColor(red: 0.722, green: 0.773, blue: 0.722, alpha: 1.000)
        static let cynicide1: UIColor = UIColor(red: 0.780, green: 0.682, blue: 0.635, alpha: 1.000)
        static let cynicide2: UIColor = UIColor(red: 0.369, green: 0.565, blue: 0.596, alpha: 1.000)
        static let cynicide3: UIColor = UIColor(red: 0.584, green: 0.580, blue: 0.463, alpha: 1.000)
        static let cynicide4: UIColor = UIColor(red: 0.263, green: 0.216, blue: 0.251, alpha: 1.000)
        static let cynicide5: UIColor = UIColor(red: 0.353, green: 0.400, blue: 0.498, alpha: 1.000)
        static let cynicide6: UIColor = UIColor(red: 0.525, green: 0.294, blue: 0.318, alpha: 1.000)
        static let cynicide7: UIColor = UIColor(red: 0.584, green: 0.659, blue: 0.804, alpha: 1.000)
        static let cynicide8: UIColor = UIColor(red: 0.847, green: 0.655, blue: 0.678, alpha: 1.000)
        static let birdsofParadise0: UIColor = UIColor(red: 0.796, green: 0.792, blue: 0.725, alpha: 1.000)
        static let birdsofParadise1: UIColor = UIColor(red: 0.898, green: 0.741, blue: 0.769, alpha: 1.000)
        static let birdsofParadise2: UIColor = UIColor(red: 0.835, green: 0.749, blue: 0.510, alpha: 1.000)
        static let birdsofParadise3: UIColor = UIColor(red: 0.400, green: 0.522, blue: 0.404, alpha: 1.000)
        static let birdsofParadise4: UIColor = UIColor(red: 0.725, green: 0.267, blue: 0.310, alpha: 1.000)
        static let birdsofParadise5: UIColor = UIColor(red: 0.506, green: 0.000, blue: 0.447, alpha: 1.000)
        static let birdsofParadise6: UIColor = UIColor(red: 0.149, green: 0.125, blue: 0.333, alpha: 1.000)
        static let birdsofParadise7: UIColor = UIColor(red: 0.404, green: 0.251, blue: 0.553, alpha: 1.000)
        static let birdsofParadise8: UIColor = UIColor(red: 0.122, green: 0.263, blue: 0.298, alpha: 1.000)
        static let brokenGlass0: UIColor = UIColor(red: 0.000, green: 0.698, blue: 0.694, alpha: 1.000)
        static let brokenGlass1: UIColor = UIColor(red: 0.235, green: 0.463, blue: 0.651, alpha: 1.000)
        static let brokenGlass2: UIColor = UIColor(red: 0.898, green: 0.616, blue: 0.082, alpha: 1.000)
        static let brokenGlass3: UIColor = UIColor(red: 0.545, green: 0.408, blue: 0.235, alpha: 1.000)
        static let brokenGlass4: UIColor = UIColor(red: 0.800, green: 0.227, blue: 0.000, alpha: 1.000)
        static let brokenGlass5: UIColor = UIColor(red: 0.722, green: 0.008, blue: 0.302, alpha: 1.000)
        static let brokenGlass6: UIColor = UIColor(red: 0.302, green: 0.000, blue: 0.157, alpha: 1.000)
        static let brokenGlass7: UIColor = UIColor(red: 0.600, green: 0.588, blue: 0.592, alpha: 1.000)
        static let brokenGlass8: UIColor = UIColor(red: 0.008, green: 0.008, blue: 0.008, alpha: 1.000)
        static let vintagePattern0: UIColor = UIColor(red: 0.898, green: 0.333, blue: 0.224, alpha: 1.000)
        static let vintagePattern1: UIColor = UIColor(red: 0.890, green: 0.847, blue: 0.518, alpha: 1.000)
        static let vintagePattern2: UIColor = UIColor(red: 0.153, green: 0.212, blue: 0.200, alpha: 1.000)
        static let vintagePattern3: UIColor = UIColor(red: 0.333, green: 0.733, blue: 0.588, alpha: 1.000)
        static let vintagePattern4: UIColor = UIColor(red: 0.514, green: 0.486, blue: 0.498, alpha: 1.000)
        static let vintagePattern5: UIColor = UIColor(red: 0.545, green: 0.796, blue: 0.859, alpha: 1.000)
        static let vintagePattern6: UIColor = UIColor(red: 0.898, green: 0.384, blue: 0.557, alpha: 1.000)
        static let vintagePattern7: UIColor = UIColor(red: 0.898, green: 0.631, blue: 0.416, alpha: 1.000)
        static let vintagePattern8: UIColor = UIColor(red: 0.867, green: 0.863, blue: 0.875, alpha: 1.000)
        static let sunset0: UIColor = UIColor(red: 0.000, green: 0.443, blue: 0.369, alpha: 1.000)
        static let sunset1: UIColor = UIColor(red: 0.275, green: 0.373, blue: 0.439, alpha: 1.000)
        static let sunset2: UIColor = UIColor(red: 0.000, green: 0.557, blue: 0.439, alpha: 1.000)
        static let sunset3: UIColor = UIColor(red: 0.278, green: 0.263, blue: 0.345, alpha: 1.000)
        static let sunset4: UIColor = UIColor(red: 0.898, green: 0.478, blue: 0.000, alpha: 1.000)
        static let sunset5: UIColor = UIColor(red: 0.749, green: 0.404, blue: 0.251, alpha: 1.000)
        static let sunset6: UIColor = UIColor(red: 0.898, green: 0.714, blue: 0.000, alpha: 1.000)
        static let sunset7: UIColor = UIColor(red: 0.753, green: 0.757, blue: 0.161, alpha: 1.000)
        static let sunset8: UIColor = UIColor(red: 0.867, green: 0.824, blue: 0.490, alpha: 1.000)
        static let rosanne0: UIColor = UIColor(red: 0.000, green: 0.165, blue: 0.239, alpha: 1.000)
        static let rosanne1: UIColor = UIColor(red: 0.702, green: 0.827, blue: 0.659, alpha: 1.000)
        static let rosanne2: UIColor = UIColor(red: 0.000, green: 0.612, blue: 0.631, alpha: 1.000)
        static let rosanne3: UIColor = UIColor(red: 0.443, green: 0.749, blue: 0.490, alpha: 1.000)
        static let rosanne4: UIColor = UIColor(red: 0.561, green: 0.671, blue: 0.686, alpha: 1.000)
        static let rosanne5: UIColor = UIColor(red: 0.898, green: 0.851, blue: 0.800, alpha: 1.000)
        static let rosanne6: UIColor = UIColor(red: 0.867, green: 0.365, blue: 0.404, alpha: 1.000)
        static let rosanne7: UIColor = UIColor(red: 0.898, green: 0.757, blue: 0.729, alpha: 1.000)
        static let rosanne8: UIColor = UIColor(red: 0.820, green: 0.000, blue: 0.298, alpha: 1.000)
        static let joyful0: UIColor = UIColor(red: 0.000, green: 0.439, blue: 0.616, alpha: 1.000)
        static let joyful1: UIColor = UIColor(red: 0.451, green: 0.694, blue: 0.812, alpha: 1.000)
        static let joyful2: UIColor = UIColor(red: 0.267, green: 0.153, blue: 0.486, alpha: 1.000)
        static let joyful3: UIColor = UIColor(red: 0.576, green: 0.525, blue: 0.702, alpha: 1.000)
        static let joyful4: UIColor = UIColor(red: 0.616, green: 0.000, blue: 0.278, alpha: 1.000)
        static let joyful5: UIColor = UIColor(red: 0.898, green: 0.545, blue: 0.486, alpha: 1.000)
        static let joyful6: UIColor = UIColor(red: 0.898, green: 0.067, blue: 0.000, alpha: 1.000)
        static let joyful7: UIColor = UIColor(red: 0.898, green: 0.780, blue: 0.416, alpha: 1.000)
        static let joyful8: UIColor = UIColor(red: 0.898, green: 0.678, blue: 0.000, alpha: 1.000)
        static let starSeeker0: UIColor = UIColor(red: 0.141, green: 0.086, blue: 0.310, alpha: 1.000)
        static let starSeeker1: UIColor = UIColor(red: 0.035, green: 0.286, blue: 0.306, alpha: 1.000)
        static let starSeeker2: UIColor = UIColor(red: 0.173, green: 0.102, blue: 0.373, alpha: 1.000)
        static let starSeeker3: UIColor = UIColor(red: 0.051, green: 0.341, blue: 0.376, alpha: 1.000)
        static let starSeeker4: UIColor = UIColor(red: 0.192, green: 0.114, blue: 0.443, alpha: 1.000)
        static let starSeeker5: UIColor = UIColor(red: 0.000, green: 0.404, blue: 0.439, alpha: 1.000)
        static let starSeeker6: UIColor = UIColor(red: 0.243, green: 0.188, blue: 0.553, alpha: 1.000)
        static let starSeeker7: UIColor = UIColor(red: 0.000, green: 0.506, blue: 0.549, alpha: 1.000)
        static let starSeeker8: UIColor = UIColor(red: 0.584, green: 0.545, blue: 0.733, alpha: 1.000)
        static let cloudyDay0: UIColor = UIColor(red: 0.153, green: 0.169, blue: 0.263, alpha: 1.000)
        static let cloudyDay1: UIColor = UIColor(red: 0.314, green: 0.243, blue: 0.157, alpha: 1.000)
        static let cloudyDay2: UIColor = UIColor(red: 0.373, green: 0.357, blue: 0.392, alpha: 1.000)
        static let cloudyDay3: UIColor = UIColor(red: 0.439, green: 0.435, blue: 0.376, alpha: 1.000)
        static let cloudyDay4: UIColor = UIColor(red: 0.616, green: 0.569, blue: 0.565, alpha: 1.000)
        static let cloudyDay5: UIColor = UIColor(red: 0.553, green: 0.655, blue: 0.616, alpha: 1.000)
        static let cloudyDay6: UIColor = UIColor(red: 0.796, green: 0.741, blue: 0.725, alpha: 1.000)
        static let cloudyDay7: UIColor = UIColor(red: 0.698, green: 0.831, blue: 0.820, alpha: 1.000)
        static let cloudyDay8: UIColor = UIColor(red: 0.878, green: 0.843, blue: 0.835, alpha: 1.000)
        static let monoPolygons0: UIColor = UIColor(red: 0.396, green: 0.169, blue: 0.439, alpha: 1.000)
        static let monoPolygons1: UIColor = UIColor(red: 0.435, green: 0.247, blue: 0.467, alpha: 1.000)
        static let monoPolygons2: UIColor = UIColor(red: 0.475, green: 0.314, blue: 0.498, alpha: 1.000)
        static let monoPolygons3: UIColor = UIColor(red: 0.518, green: 0.373, blue: 0.533, alpha: 1.000)
        static let monoPolygons4: UIColor = UIColor(red: 0.569, green: 0.443, blue: 0.569, alpha: 1.000)
        static let monoPolygons5: UIColor = UIColor(red: 0.620, green: 0.514, blue: 0.612, alpha: 1.000)
        static let monoPolygons6: UIColor = UIColor(red: 0.675, green: 0.600, blue: 0.655, alpha: 1.000)
        static let monoPolygons7: UIColor = UIColor(red: 0.737, green: 0.686, blue: 0.710, alpha: 1.000)
        static let monoPolygons8: UIColor = UIColor(red: 0.808, green: 0.784, blue: 0.761, alpha: 1.000)
        static var imageOfAlignmentRightSelected: UIImage?
        static var alignmentRightSelectedTargets: [AnyObject]?
        static var imageOfAlignmentRightNormal: UIImage?
        static var alignmentRightNormalTargets: [AnyObject]?
        static var imageOfAlignmentLeftSelected: UIImage?
        static var alignmentLeftSelectedTargets: [AnyObject]?
        static var imageOfAlignmentLeftNormal: UIImage?
        static var alignmentLeftNormalTargets: [AnyObject]?
        static var imageOfAlignmentCenterSelected: UIImage?
        static var alignmentCenterSelectedTargets: [AnyObject]?
        static var imageOfAlignmentCenterNormal: UIImage?
        static var alignmentCenterNormalTargets: [AnyObject]?
        static var imageOfAlignmentJustNormal: UIImage?
        static var alignmentJustNormalTargets: [AnyObject]?
        static var imageOfAlignmentJustSelected: UIImage?
        static var alignmentJustSelectedTargets: [AnyObject]?
        static var imageOfLineSpacingNormal: UIImage?
        static var lineSpacingNormalTargets: [AnyObject]?
        static var imageOfLineSpacingSelected: UIImage?
        static var lineSpacingSelectedTargets: [AnyObject]?
        static var imageOfTextSpacingSelected: UIImage?
        static var textSpacingSelectedTargets: [AnyObject]?
        static var imageOfTextSpacingNormal: UIImage?
        static var textSpacingNormalTargets: [AnyObject]?
    }

    //// Colors

    public class var normalColor: UIColor { return Cache.normalColor }
    public class var selectedColor: UIColor { return Cache.selectedColor }
    public class var red0: UIColor { return Cache.red0 }
    public class var red1: UIColor { return Cache.red1 }
    public class var red2: UIColor { return Cache.red2 }
    public class var red3: UIColor { return Cache.red3 }
    public class var red4: UIColor { return Cache.red4 }
    public class var red5: UIColor { return Cache.red5 }
    public class var red6: UIColor { return Cache.red6 }
    public class var red7: UIColor { return Cache.red7 }
    public class var red8: UIColor { return Cache.red8 }
    public class var yellow0: UIColor { return Cache.yellow0 }
    public class var yellow1: UIColor { return Cache.yellow1 }
    public class var yellow2: UIColor { return Cache.yellow2 }
    public class var yellow3: UIColor { return Cache.yellow3 }
    public class var yellow4: UIColor { return Cache.yellow4 }
    public class var yellow5: UIColor { return Cache.yellow5 }
    public class var yellow6: UIColor { return Cache.yellow6 }
    public class var yellow7: UIColor { return Cache.yellow7 }
    public class var yellow8: UIColor { return Cache.yellow8 }
    public class var blue0: UIColor { return Cache.blue0 }
    public class var blue1: UIColor { return Cache.blue1 }
    public class var blue2: UIColor { return Cache.blue2 }
    public class var blue3: UIColor { return Cache.blue3 }
    public class var blue4: UIColor { return Cache.blue4 }
    public class var blue5: UIColor { return Cache.blue5 }
    public class var blue6: UIColor { return Cache.blue6 }
    public class var blue7: UIColor { return Cache.blue7 }
    public class var blue8: UIColor { return Cache.blue8 }
    public class var green0: UIColor { return Cache.green0 }
    public class var green1: UIColor { return Cache.green1 }
    public class var green2: UIColor { return Cache.green2 }
    public class var green3: UIColor { return Cache.green3 }
    public class var green4: UIColor { return Cache.green4 }
    public class var green5: UIColor { return Cache.green5 }
    public class var green6: UIColor { return Cache.green6 }
    public class var green7: UIColor { return Cache.green7 }
    public class var green8: UIColor { return Cache.green8 }
    public class var orange0: UIColor { return Cache.orange0 }
    public class var orange1: UIColor { return Cache.orange1 }
    public class var orange2: UIColor { return Cache.orange2 }
    public class var orange3: UIColor { return Cache.orange3 }
    public class var orange4: UIColor { return Cache.orange4 }
    public class var orange5: UIColor { return Cache.orange5 }
    public class var orange6: UIColor { return Cache.orange6 }
    public class var orange7: UIColor { return Cache.orange7 }
    public class var orange8: UIColor { return Cache.orange8 }
    public class var indigo0: UIColor { return Cache.indigo0 }
    public class var indigo1: UIColor { return Cache.indigo1 }
    public class var indigo2: UIColor { return Cache.indigo2 }
    public class var indigo3: UIColor { return Cache.indigo3 }
    public class var indigo4: UIColor { return Cache.indigo4 }
    public class var indigo5: UIColor { return Cache.indigo5 }
    public class var indigo6: UIColor { return Cache.indigo6 }
    public class var indigo7: UIColor { return Cache.indigo7 }
    public class var indigo8: UIColor { return Cache.indigo8 }
    public class var purple0: UIColor { return Cache.purple0 }
    public class var purple1: UIColor { return Cache.purple1 }
    public class var purple2: UIColor { return Cache.purple2 }
    public class var purple3: UIColor { return Cache.purple3 }
    public class var purple4: UIColor { return Cache.purple4 }
    public class var purple5: UIColor { return Cache.purple5 }
    public class var purple6: UIColor { return Cache.purple6 }
    public class var purple7: UIColor { return Cache.purple7 }
    public class var purple8: UIColor { return Cache.purple8 }
    public class var black0: UIColor { return Cache.black0 }
    public class var black1: UIColor { return Cache.black1 }
    public class var black2: UIColor { return Cache.black2 }
    public class var black3: UIColor { return Cache.black3 }
    public class var black4: UIColor { return Cache.black4 }
    public class var black5: UIColor { return Cache.black5 }
    public class var black6: UIColor { return Cache.black6 }
    public class var black7: UIColor { return Cache.black7 }
    public class var black8: UIColor { return Cache.black8 }
    public class var salamander0: UIColor { return Cache.salamander0 }
    public class var salamander1: UIColor { return Cache.salamander1 }
    public class var salamander2: UIColor { return Cache.salamander2 }
    public class var salamander3: UIColor { return Cache.salamander3 }
    public class var salamander4: UIColor { return Cache.salamander4 }
    public class var salamander5: UIColor { return Cache.salamander5 }
    public class var salamander6: UIColor { return Cache.salamander6 }
    public class var salamander7: UIColor { return Cache.salamander7 }
    public class var salamander8: UIColor { return Cache.salamander8 }
    public class var intoDreams0: UIColor { return Cache.intoDreams0 }
    public class var intoDreams1: UIColor { return Cache.intoDreams1 }
    public class var intoDreams2: UIColor { return Cache.intoDreams2 }
    public class var intoDreams3: UIColor { return Cache.intoDreams3 }
    public class var intoDreams4: UIColor { return Cache.intoDreams4 }
    public class var intoDreams5: UIColor { return Cache.intoDreams5 }
    public class var intoDreams6: UIColor { return Cache.intoDreams6 }
    public class var intoDreams7: UIColor { return Cache.intoDreams7 }
    public class var intoDreams8: UIColor { return Cache.intoDreams8 }
    public class var cynicide0: UIColor { return Cache.cynicide0 }
    public class var cynicide1: UIColor { return Cache.cynicide1 }
    public class var cynicide2: UIColor { return Cache.cynicide2 }
    public class var cynicide3: UIColor { return Cache.cynicide3 }
    public class var cynicide4: UIColor { return Cache.cynicide4 }
    public class var cynicide5: UIColor { return Cache.cynicide5 }
    public class var cynicide6: UIColor { return Cache.cynicide6 }
    public class var cynicide7: UIColor { return Cache.cynicide7 }
    public class var cynicide8: UIColor { return Cache.cynicide8 }
    public class var birdsofParadise0: UIColor { return Cache.birdsofParadise0 }
    public class var birdsofParadise1: UIColor { return Cache.birdsofParadise1 }
    public class var birdsofParadise2: UIColor { return Cache.birdsofParadise2 }
    public class var birdsofParadise3: UIColor { return Cache.birdsofParadise3 }
    public class var birdsofParadise4: UIColor { return Cache.birdsofParadise4 }
    public class var birdsofParadise5: UIColor { return Cache.birdsofParadise5 }
    public class var birdsofParadise6: UIColor { return Cache.birdsofParadise6 }
    public class var birdsofParadise7: UIColor { return Cache.birdsofParadise7 }
    public class var birdsofParadise8: UIColor { return Cache.birdsofParadise8 }
    public class var brokenGlass0: UIColor { return Cache.brokenGlass0 }
    public class var brokenGlass1: UIColor { return Cache.brokenGlass1 }
    public class var brokenGlass2: UIColor { return Cache.brokenGlass2 }
    public class var brokenGlass3: UIColor { return Cache.brokenGlass3 }
    public class var brokenGlass4: UIColor { return Cache.brokenGlass4 }
    public class var brokenGlass5: UIColor { return Cache.brokenGlass5 }
    public class var brokenGlass6: UIColor { return Cache.brokenGlass6 }
    public class var brokenGlass7: UIColor { return Cache.brokenGlass7 }
    public class var brokenGlass8: UIColor { return Cache.brokenGlass8 }
    public class var vintagePattern0: UIColor { return Cache.vintagePattern0 }
    public class var vintagePattern1: UIColor { return Cache.vintagePattern1 }
    public class var vintagePattern2: UIColor { return Cache.vintagePattern2 }
    public class var vintagePattern3: UIColor { return Cache.vintagePattern3 }
    public class var vintagePattern4: UIColor { return Cache.vintagePattern4 }
    public class var vintagePattern5: UIColor { return Cache.vintagePattern5 }
    public class var vintagePattern6: UIColor { return Cache.vintagePattern6 }
    public class var vintagePattern7: UIColor { return Cache.vintagePattern7 }
    public class var vintagePattern8: UIColor { return Cache.vintagePattern8 }
    public class var sunset0: UIColor { return Cache.sunset0 }
    public class var sunset1: UIColor { return Cache.sunset1 }
    public class var sunset2: UIColor { return Cache.sunset2 }
    public class var sunset3: UIColor { return Cache.sunset3 }
    public class var sunset4: UIColor { return Cache.sunset4 }
    public class var sunset5: UIColor { return Cache.sunset5 }
    public class var sunset6: UIColor { return Cache.sunset6 }
    public class var sunset7: UIColor { return Cache.sunset7 }
    public class var sunset8: UIColor { return Cache.sunset8 }
    public class var rosanne0: UIColor { return Cache.rosanne0 }
    public class var rosanne1: UIColor { return Cache.rosanne1 }
    public class var rosanne2: UIColor { return Cache.rosanne2 }
    public class var rosanne3: UIColor { return Cache.rosanne3 }
    public class var rosanne4: UIColor { return Cache.rosanne4 }
    public class var rosanne5: UIColor { return Cache.rosanne5 }
    public class var rosanne6: UIColor { return Cache.rosanne6 }
    public class var rosanne7: UIColor { return Cache.rosanne7 }
    public class var rosanne8: UIColor { return Cache.rosanne8 }
    public class var joyful0: UIColor { return Cache.joyful0 }
    public class var joyful1: UIColor { return Cache.joyful1 }
    public class var joyful2: UIColor { return Cache.joyful2 }
    public class var joyful3: UIColor { return Cache.joyful3 }
    public class var joyful4: UIColor { return Cache.joyful4 }
    public class var joyful5: UIColor { return Cache.joyful5 }
    public class var joyful6: UIColor { return Cache.joyful6 }
    public class var joyful7: UIColor { return Cache.joyful7 }
    public class var joyful8: UIColor { return Cache.joyful8 }
    public class var starSeeker0: UIColor { return Cache.starSeeker0 }
    public class var starSeeker1: UIColor { return Cache.starSeeker1 }
    public class var starSeeker2: UIColor { return Cache.starSeeker2 }
    public class var starSeeker3: UIColor { return Cache.starSeeker3 }
    public class var starSeeker4: UIColor { return Cache.starSeeker4 }
    public class var starSeeker5: UIColor { return Cache.starSeeker5 }
    public class var starSeeker6: UIColor { return Cache.starSeeker6 }
    public class var starSeeker7: UIColor { return Cache.starSeeker7 }
    public class var starSeeker8: UIColor { return Cache.starSeeker8 }
    public class var cloudyDay0: UIColor { return Cache.cloudyDay0 }
    public class var cloudyDay1: UIColor { return Cache.cloudyDay1 }
    public class var cloudyDay2: UIColor { return Cache.cloudyDay2 }
    public class var cloudyDay3: UIColor { return Cache.cloudyDay3 }
    public class var cloudyDay4: UIColor { return Cache.cloudyDay4 }
    public class var cloudyDay5: UIColor { return Cache.cloudyDay5 }
    public class var cloudyDay6: UIColor { return Cache.cloudyDay6 }
    public class var cloudyDay7: UIColor { return Cache.cloudyDay7 }
    public class var cloudyDay8: UIColor { return Cache.cloudyDay8 }
    public class var monoPolygons0: UIColor { return Cache.monoPolygons0 }
    public class var monoPolygons1: UIColor { return Cache.monoPolygons1 }
    public class var monoPolygons2: UIColor { return Cache.monoPolygons2 }
    public class var monoPolygons3: UIColor { return Cache.monoPolygons3 }
    public class var monoPolygons4: UIColor { return Cache.monoPolygons4 }
    public class var monoPolygons5: UIColor { return Cache.monoPolygons5 }
    public class var monoPolygons6: UIColor { return Cache.monoPolygons6 }
    public class var monoPolygons7: UIColor { return Cache.monoPolygons7 }
    public class var monoPolygons8: UIColor { return Cache.monoPolygons8 }

    //// Drawing Methods

    public class func drawAlignmentRightSelected() {

        //// Bezier Drawing
        let bezierPath = UIBezierPath()
        bezierPath.moveToPoint(CGPointMake(0, 0))
        bezierPath.addLineToPoint(CGPointMake(30, 0))
        bezierPath.addLineToPoint(CGPointMake(30, 3.36))
        bezierPath.addLineToPoint(CGPointMake(0, 3.36))
        bezierPath.addLineToPoint(CGPointMake(0, 0))
        bezierPath.closePath()
        bezierPath.moveToPoint(CGPointMake(10, 10))
        bezierPath.addLineToPoint(CGPointMake(10, 6.64))
        bezierPath.addLineToPoint(CGPointMake(30, 6.64))
        bezierPath.addLineToPoint(CGPointMake(30, 10))
        bezierPath.addLineToPoint(CGPointMake(10, 10))
        bezierPath.closePath()
        bezierPath.moveToPoint(CGPointMake(0, 16.64))
        bezierPath.addLineToPoint(CGPointMake(0, 13.36))
        bezierPath.addLineToPoint(CGPointMake(30, 13.36))
        bezierPath.addLineToPoint(CGPointMake(30, 16.64))
        bezierPath.addLineToPoint(CGPointMake(0, 16.64))
        bezierPath.closePath()
        bezierPath.moveToPoint(CGPointMake(10, 23.36))
        bezierPath.addLineToPoint(CGPointMake(10, 20))
        bezierPath.addLineToPoint(CGPointMake(30, 20))
        bezierPath.addLineToPoint(CGPointMake(30, 23.36))
        bezierPath.addLineToPoint(CGPointMake(10, 23.36))
        bezierPath.closePath()
        bezierPath.moveToPoint(CGPointMake(0, 30))
        bezierPath.addLineToPoint(CGPointMake(0, 26.64))
        bezierPath.addLineToPoint(CGPointMake(30, 26.64))
        bezierPath.addLineToPoint(CGPointMake(30, 30))
        bezierPath.addLineToPoint(CGPointMake(0, 30))
        bezierPath.closePath()
        bezierPath.miterLimit = 4;

        CTAStyleKit.selectedColor.setFill()
        bezierPath.fill()
    }

    public class func drawAlignmentRightNormal() {

        //// Bezier Drawing
        let bezierPath = UIBezierPath()
        bezierPath.moveToPoint(CGPointMake(0, 0))
        bezierPath.addLineToPoint(CGPointMake(30, 0))
        bezierPath.addLineToPoint(CGPointMake(30, 3.36))
        bezierPath.addLineToPoint(CGPointMake(0, 3.36))
        bezierPath.addLineToPoint(CGPointMake(0, 0))
        bezierPath.closePath()
        bezierPath.moveToPoint(CGPointMake(10, 10))
        bezierPath.addLineToPoint(CGPointMake(10, 6.64))
        bezierPath.addLineToPoint(CGPointMake(30, 6.64))
        bezierPath.addLineToPoint(CGPointMake(30, 10))
        bezierPath.addLineToPoint(CGPointMake(10, 10))
        bezierPath.closePath()
        bezierPath.moveToPoint(CGPointMake(0, 16.64))
        bezierPath.addLineToPoint(CGPointMake(0, 13.36))
        bezierPath.addLineToPoint(CGPointMake(30, 13.36))
        bezierPath.addLineToPoint(CGPointMake(30, 16.64))
        bezierPath.addLineToPoint(CGPointMake(0, 16.64))
        bezierPath.closePath()
        bezierPath.moveToPoint(CGPointMake(10, 23.36))
        bezierPath.addLineToPoint(CGPointMake(10, 20))
        bezierPath.addLineToPoint(CGPointMake(30, 20))
        bezierPath.addLineToPoint(CGPointMake(30, 23.36))
        bezierPath.addLineToPoint(CGPointMake(10, 23.36))
        bezierPath.closePath()
        bezierPath.moveToPoint(CGPointMake(0, 30))
        bezierPath.addLineToPoint(CGPointMake(0, 26.64))
        bezierPath.addLineToPoint(CGPointMake(30, 26.64))
        bezierPath.addLineToPoint(CGPointMake(30, 30))
        bezierPath.addLineToPoint(CGPointMake(0, 30))
        bezierPath.closePath()
        bezierPath.miterLimit = 4;

        CTAStyleKit.normalColor.setFill()
        bezierPath.fill()
    }

    public class func drawAlignmentLeftSelected() {

        //// Bezier Drawing
        let bezierPath = UIBezierPath()
        bezierPath.moveToPoint(CGPointMake(0, 0))
        bezierPath.addLineToPoint(CGPointMake(30, 0))
        bezierPath.addLineToPoint(CGPointMake(30, 3.36))
        bezierPath.addLineToPoint(CGPointMake(0, 3.36))
        bezierPath.addLineToPoint(CGPointMake(0, 0))
        bezierPath.closePath()
        bezierPath.moveToPoint(CGPointMake(0, 30))
        bezierPath.addLineToPoint(CGPointMake(0, 26.64))
        bezierPath.addLineToPoint(CGPointMake(30, 26.64))
        bezierPath.addLineToPoint(CGPointMake(30, 30))
        bezierPath.addLineToPoint(CGPointMake(0, 30))
        bezierPath.closePath()
        bezierPath.moveToPoint(CGPointMake(0, 16.64))
        bezierPath.addLineToPoint(CGPointMake(0, 13.36))
        bezierPath.addLineToPoint(CGPointMake(30, 13.36))
        bezierPath.addLineToPoint(CGPointMake(30, 16.64))
        bezierPath.addLineToPoint(CGPointMake(0, 16.64))
        bezierPath.closePath()
        bezierPath.moveToPoint(CGPointMake(20, 6.64))
        bezierPath.addLineToPoint(CGPointMake(20, 10))
        bezierPath.addLineToPoint(CGPointMake(0, 10))
        bezierPath.addLineToPoint(CGPointMake(0, 6.64))
        bezierPath.addLineToPoint(CGPointMake(20, 6.64))
        bezierPath.closePath()
        bezierPath.moveToPoint(CGPointMake(20, 20))
        bezierPath.addLineToPoint(CGPointMake(20, 23.36))
        bezierPath.addLineToPoint(CGPointMake(0, 23.36))
        bezierPath.addLineToPoint(CGPointMake(0, 20))
        bezierPath.addLineToPoint(CGPointMake(20, 20))
        bezierPath.closePath()
        bezierPath.miterLimit = 4;

        CTAStyleKit.selectedColor.setFill()
        bezierPath.fill()
    }

    public class func drawAlignmentLeftNormal() {

        //// Bezier Drawing
        let bezierPath = UIBezierPath()
        bezierPath.moveToPoint(CGPointMake(0, 0))
        bezierPath.addLineToPoint(CGPointMake(30, 0))
        bezierPath.addLineToPoint(CGPointMake(30, 3.36))
        bezierPath.addLineToPoint(CGPointMake(0, 3.36))
        bezierPath.addLineToPoint(CGPointMake(0, 0))
        bezierPath.closePath()
        bezierPath.moveToPoint(CGPointMake(0, 30))
        bezierPath.addLineToPoint(CGPointMake(0, 26.64))
        bezierPath.addLineToPoint(CGPointMake(30, 26.64))
        bezierPath.addLineToPoint(CGPointMake(30, 30))
        bezierPath.addLineToPoint(CGPointMake(0, 30))
        bezierPath.closePath()
        bezierPath.moveToPoint(CGPointMake(0, 16.64))
        bezierPath.addLineToPoint(CGPointMake(0, 13.36))
        bezierPath.addLineToPoint(CGPointMake(30, 13.36))
        bezierPath.addLineToPoint(CGPointMake(30, 16.64))
        bezierPath.addLineToPoint(CGPointMake(0, 16.64))
        bezierPath.closePath()
        bezierPath.moveToPoint(CGPointMake(20, 6.64))
        bezierPath.addLineToPoint(CGPointMake(20, 10))
        bezierPath.addLineToPoint(CGPointMake(0, 10))
        bezierPath.addLineToPoint(CGPointMake(0, 6.64))
        bezierPath.addLineToPoint(CGPointMake(20, 6.64))
        bezierPath.closePath()
        bezierPath.moveToPoint(CGPointMake(20, 20))
        bezierPath.addLineToPoint(CGPointMake(20, 23.36))
        bezierPath.addLineToPoint(CGPointMake(0, 23.36))
        bezierPath.addLineToPoint(CGPointMake(0, 20))
        bezierPath.addLineToPoint(CGPointMake(20, 20))
        bezierPath.closePath()
        bezierPath.miterLimit = 4;

        CTAStyleKit.normalColor.setFill()
        bezierPath.fill()
    }

    public class func drawAlignmentCenterSelected() {

        //// Bezier Drawing
        let bezierPath = UIBezierPath()
        bezierPath.moveToPoint(CGPointMake(0, 0))
        bezierPath.addLineToPoint(CGPointMake(30, 0))
        bezierPath.addLineToPoint(CGPointMake(30, 3.36))
        bezierPath.addLineToPoint(CGPointMake(0, 3.36))
        bezierPath.addLineToPoint(CGPointMake(0, 0))
        bezierPath.closePath()
        bezierPath.moveToPoint(CGPointMake(6.64, 6.64))
        bezierPath.addLineToPoint(CGPointMake(23.36, 6.64))
        bezierPath.addLineToPoint(CGPointMake(23.36, 10))
        bezierPath.addLineToPoint(CGPointMake(6.64, 10))
        bezierPath.addLineToPoint(CGPointMake(6.64, 6.64))
        bezierPath.closePath()
        bezierPath.moveToPoint(CGPointMake(0, 16.64))
        bezierPath.addLineToPoint(CGPointMake(0, 13.36))
        bezierPath.addLineToPoint(CGPointMake(30, 13.36))
        bezierPath.addLineToPoint(CGPointMake(30, 16.64))
        bezierPath.addLineToPoint(CGPointMake(0, 16.64))
        bezierPath.closePath()
        bezierPath.moveToPoint(CGPointMake(0, 30))
        bezierPath.addLineToPoint(CGPointMake(0, 26.64))
        bezierPath.addLineToPoint(CGPointMake(30, 26.64))
        bezierPath.addLineToPoint(CGPointMake(30, 30))
        bezierPath.addLineToPoint(CGPointMake(0, 30))
        bezierPath.closePath()
        bezierPath.moveToPoint(CGPointMake(6.64, 20))
        bezierPath.addLineToPoint(CGPointMake(23.36, 20))
        bezierPath.addLineToPoint(CGPointMake(23.36, 23.36))
        bezierPath.addLineToPoint(CGPointMake(6.64, 23.36))
        bezierPath.addLineToPoint(CGPointMake(6.64, 20))
        bezierPath.closePath()
        bezierPath.miterLimit = 4;

        CTAStyleKit.selectedColor.setFill()
        bezierPath.fill()
    }

    public class func drawAlignmentCenterNormal() {

        //// Bezier Drawing
        let bezierPath = UIBezierPath()
        bezierPath.moveToPoint(CGPointMake(0, 0))
        bezierPath.addLineToPoint(CGPointMake(30, 0))
        bezierPath.addLineToPoint(CGPointMake(30, 3.36))
        bezierPath.addLineToPoint(CGPointMake(0, 3.36))
        bezierPath.addLineToPoint(CGPointMake(0, 0))
        bezierPath.closePath()
        bezierPath.moveToPoint(CGPointMake(6.64, 6.64))
        bezierPath.addLineToPoint(CGPointMake(23.36, 6.64))
        bezierPath.addLineToPoint(CGPointMake(23.36, 10))
        bezierPath.addLineToPoint(CGPointMake(6.64, 10))
        bezierPath.addLineToPoint(CGPointMake(6.64, 6.64))
        bezierPath.closePath()
        bezierPath.moveToPoint(CGPointMake(0, 16.64))
        bezierPath.addLineToPoint(CGPointMake(0, 13.36))
        bezierPath.addLineToPoint(CGPointMake(30, 13.36))
        bezierPath.addLineToPoint(CGPointMake(30, 16.64))
        bezierPath.addLineToPoint(CGPointMake(0, 16.64))
        bezierPath.closePath()
        bezierPath.moveToPoint(CGPointMake(0, 30))
        bezierPath.addLineToPoint(CGPointMake(0, 26.64))
        bezierPath.addLineToPoint(CGPointMake(30, 26.64))
        bezierPath.addLineToPoint(CGPointMake(30, 30))
        bezierPath.addLineToPoint(CGPointMake(0, 30))
        bezierPath.closePath()
        bezierPath.moveToPoint(CGPointMake(6.64, 20))
        bezierPath.addLineToPoint(CGPointMake(23.36, 20))
        bezierPath.addLineToPoint(CGPointMake(23.36, 23.36))
        bezierPath.addLineToPoint(CGPointMake(6.64, 23.36))
        bezierPath.addLineToPoint(CGPointMake(6.64, 20))
        bezierPath.closePath()
        bezierPath.miterLimit = 4;

        CTAStyleKit.normalColor.setFill()
        bezierPath.fill()
    }

    public class func drawAlignmentJustNormal() {

        //// alignment-Just-Normal Drawing
        let alignmentJustNormalPath = UIBezierPath()
        alignmentJustNormalPath.moveToPoint(CGPointMake(0, 0))
        alignmentJustNormalPath.addLineToPoint(CGPointMake(30, 0))
        alignmentJustNormalPath.addLineToPoint(CGPointMake(30, 3.36))
        alignmentJustNormalPath.addLineToPoint(CGPointMake(0, 3.36))
        alignmentJustNormalPath.addLineToPoint(CGPointMake(0, 0))
        alignmentJustNormalPath.closePath()
        alignmentJustNormalPath.moveToPoint(CGPointMake(0, 10))
        alignmentJustNormalPath.addLineToPoint(CGPointMake(0, 6.64))
        alignmentJustNormalPath.addLineToPoint(CGPointMake(30, 6.64))
        alignmentJustNormalPath.addLineToPoint(CGPointMake(30, 10))
        alignmentJustNormalPath.addLineToPoint(CGPointMake(0, 10))
        alignmentJustNormalPath.closePath()
        alignmentJustNormalPath.moveToPoint(CGPointMake(0, 16.64))
        alignmentJustNormalPath.addLineToPoint(CGPointMake(0, 13.36))
        alignmentJustNormalPath.addLineToPoint(CGPointMake(30, 13.36))
        alignmentJustNormalPath.addLineToPoint(CGPointMake(30, 16.64))
        alignmentJustNormalPath.addLineToPoint(CGPointMake(0, 16.64))
        alignmentJustNormalPath.closePath()
        alignmentJustNormalPath.moveToPoint(CGPointMake(0, 23.36))
        alignmentJustNormalPath.addLineToPoint(CGPointMake(0, 20))
        alignmentJustNormalPath.addLineToPoint(CGPointMake(30, 20))
        alignmentJustNormalPath.addLineToPoint(CGPointMake(30, 23.36))
        alignmentJustNormalPath.addLineToPoint(CGPointMake(0, 23.36))
        alignmentJustNormalPath.closePath()
        alignmentJustNormalPath.moveToPoint(CGPointMake(0, 30))
        alignmentJustNormalPath.addLineToPoint(CGPointMake(0, 26.64))
        alignmentJustNormalPath.addLineToPoint(CGPointMake(30, 26.64))
        alignmentJustNormalPath.addLineToPoint(CGPointMake(30, 30))
        alignmentJustNormalPath.addLineToPoint(CGPointMake(0, 30))
        alignmentJustNormalPath.closePath()
        alignmentJustNormalPath.miterLimit = 4;

        CTAStyleKit.normalColor.setFill()
        alignmentJustNormalPath.fill()
    }

    public class func drawAlignmentJustSelected() {

        //// Bezier 2 Drawing
        let bezier2Path = UIBezierPath()
        bezier2Path.moveToPoint(CGPointMake(0, 0))
        bezier2Path.addLineToPoint(CGPointMake(30, 0))
        bezier2Path.addLineToPoint(CGPointMake(30, 3.36))
        bezier2Path.addLineToPoint(CGPointMake(0, 3.36))
        bezier2Path.addLineToPoint(CGPointMake(0, 0))
        bezier2Path.closePath()
        bezier2Path.moveToPoint(CGPointMake(0, 10))
        bezier2Path.addLineToPoint(CGPointMake(0, 6.64))
        bezier2Path.addLineToPoint(CGPointMake(30, 6.64))
        bezier2Path.addLineToPoint(CGPointMake(30, 10))
        bezier2Path.addLineToPoint(CGPointMake(0, 10))
        bezier2Path.closePath()
        bezier2Path.moveToPoint(CGPointMake(0, 16.64))
        bezier2Path.addLineToPoint(CGPointMake(0, 13.36))
        bezier2Path.addLineToPoint(CGPointMake(30, 13.36))
        bezier2Path.addLineToPoint(CGPointMake(30, 16.64))
        bezier2Path.addLineToPoint(CGPointMake(0, 16.64))
        bezier2Path.closePath()
        bezier2Path.moveToPoint(CGPointMake(0, 23.36))
        bezier2Path.addLineToPoint(CGPointMake(0, 20))
        bezier2Path.addLineToPoint(CGPointMake(30, 20))
        bezier2Path.addLineToPoint(CGPointMake(30, 23.36))
        bezier2Path.addLineToPoint(CGPointMake(0, 23.36))
        bezier2Path.closePath()
        bezier2Path.moveToPoint(CGPointMake(0, 30))
        bezier2Path.addLineToPoint(CGPointMake(0, 26.64))
        bezier2Path.addLineToPoint(CGPointMake(30, 26.64))
        bezier2Path.addLineToPoint(CGPointMake(30, 30))
        bezier2Path.addLineToPoint(CGPointMake(0, 30))
        bezier2Path.closePath()
        bezier2Path.miterLimit = 4;

        CTAStyleKit.selectedColor.setFill()
        bezier2Path.fill()
    }

    public class func drawLineSpacingNormal() {

        //// Bezier Drawing
        let bezierPath = UIBezierPath()
        bezierPath.moveToPoint(CGPointMake(18.27, 5.33))
        bezierPath.addCurveToPoint(CGPointMake(19.65, 5.36), controlPoint1: CGPointMake(18.72, 5.8), controlPoint2: CGPointMake(19.18, 5.81))
        bezierPath.addCurveToPoint(CGPointMake(19.62, 4.04), controlPoint1: CGPointMake(20.13, 4.91), controlPoint2: CGPointMake(20.12, 4.47))
        bezierPath.addLineToPoint(CGPointMake(15.68, 0.29))
        bezierPath.addCurveToPoint(CGPointMake(15.37, 0.06), controlPoint1: CGPointMake(15.6, 0.18), controlPoint2: CGPointMake(15.49, 0.1))
        bezierPath.addCurveToPoint(CGPointMake(14.63, 0.06), controlPoint1: CGPointMake(15.12, -0.02), controlPoint2: CGPointMake(14.88, -0.02))
        bezierPath.addCurveToPoint(CGPointMake(14.32, 0.29), controlPoint1: CGPointMake(14.51, 0.1), controlPoint2: CGPointMake(14.4, 0.18))
        bezierPath.addLineToPoint(CGPointMake(10.38, 4.04))
        bezierPath.addCurveToPoint(CGPointMake(10.35, 5.36), controlPoint1: CGPointMake(9.88, 4.47), controlPoint2: CGPointMake(9.87, 4.91))
        bezierPath.addCurveToPoint(CGPointMake(11.73, 5.33), controlPoint1: CGPointMake(10.82, 5.81), controlPoint2: CGPointMake(11.28, 5.8))
        bezierPath.addLineToPoint(CGPointMake(14.01, 3.22))
        bezierPath.addLineToPoint(CGPointMake(14.01, 26.78))
        bezierPath.addLineToPoint(CGPointMake(11.73, 24.67))
        bezierPath.addCurveToPoint(CGPointMake(10.35, 24.64), controlPoint1: CGPointMake(11.28, 24.2), controlPoint2: CGPointMake(10.82, 24.19))
        bezierPath.addCurveToPoint(CGPointMake(10.38, 25.96), controlPoint1: CGPointMake(9.87, 25.09), controlPoint2: CGPointMake(9.88, 25.53))
        bezierPath.addLineToPoint(CGPointMake(14.32, 29.71))
        bezierPath.addCurveToPoint(CGPointMake(14.63, 29.94), controlPoint1: CGPointMake(14.4, 29.82), controlPoint2: CGPointMake(14.51, 29.9))
        bezierPath.addCurveToPoint(CGPointMake(15.37, 29.94), controlPoint1: CGPointMake(14.88, 30.02), controlPoint2: CGPointMake(15.12, 30.02))
        bezierPath.addCurveToPoint(CGPointMake(15.68, 29.71), controlPoint1: CGPointMake(15.49, 29.9), controlPoint2: CGPointMake(15.6, 29.82))
        bezierPath.addLineToPoint(CGPointMake(19.62, 25.96))
        bezierPath.addCurveToPoint(CGPointMake(19.65, 24.64), controlPoint1: CGPointMake(20.12, 25.53), controlPoint2: CGPointMake(20.13, 25.09))
        bezierPath.addCurveToPoint(CGPointMake(18.27, 24.67), controlPoint1: CGPointMake(19.18, 24.19), controlPoint2: CGPointMake(18.72, 24.2))
        bezierPath.addLineToPoint(CGPointMake(15.99, 26.78))
        bezierPath.addLineToPoint(CGPointMake(15.99, 3.22))
        bezierPath.addLineToPoint(CGPointMake(18.27, 5.33))
        bezierPath.closePath()
        bezierPath.miterLimit = 4;

        CTAStyleKit.normalColor.setFill()
        bezierPath.fill()
    }

    public class func drawCanvas2() {
        //// Color Declarations
        let fillColor = UIColor(red: 0.000, green: 0.000, blue: 0.000, alpha: 1.000)

        //// Bezier Drawing
        let bezierPath = UIBezierPath()
        bezierPath.moveToPoint(CGPointMake(78.27, 51.33))
        bezierPath.addCurveToPoint(CGPointMake(79.65, 51.36), controlPoint1: CGPointMake(78.72, 51.8), controlPoint2: CGPointMake(79.18, 51.81))
        bezierPath.addCurveToPoint(CGPointMake(79.62, 50.04), controlPoint1: CGPointMake(80.13, 50.91), controlPoint2: CGPointMake(80.12, 50.47))
        bezierPath.addLineToPoint(CGPointMake(75.68, 46.29))
        bezierPath.addCurveToPoint(CGPointMake(75.37, 46.06), controlPoint1: CGPointMake(75.6, 46.18), controlPoint2: CGPointMake(75.49, 46.1))
        bezierPath.addCurveToPoint(CGPointMake(74.63, 46.06), controlPoint1: CGPointMake(75.12, 45.98), controlPoint2: CGPointMake(74.88, 45.98))
        bezierPath.addCurveToPoint(CGPointMake(74.32, 46.29), controlPoint1: CGPointMake(74.51, 46.1), controlPoint2: CGPointMake(74.4, 46.18))
        bezierPath.addLineToPoint(CGPointMake(70.38, 50.04))
        bezierPath.addCurveToPoint(CGPointMake(70.35, 51.36), controlPoint1: CGPointMake(69.88, 50.47), controlPoint2: CGPointMake(69.87, 50.91))
        bezierPath.addCurveToPoint(CGPointMake(71.73, 51.33), controlPoint1: CGPointMake(70.82, 51.81), controlPoint2: CGPointMake(71.28, 51.8))
        bezierPath.addLineToPoint(CGPointMake(74.01, 49.22))
        bezierPath.addLineToPoint(CGPointMake(74.01, 72.78))
        bezierPath.addLineToPoint(CGPointMake(71.73, 70.67))
        bezierPath.addCurveToPoint(CGPointMake(70.35, 70.64), controlPoint1: CGPointMake(71.28, 70.2), controlPoint2: CGPointMake(70.82, 70.19))
        bezierPath.addCurveToPoint(CGPointMake(70.38, 71.96), controlPoint1: CGPointMake(69.87, 71.09), controlPoint2: CGPointMake(69.88, 71.53))
        bezierPath.addLineToPoint(CGPointMake(74.32, 75.71))
        bezierPath.addCurveToPoint(CGPointMake(74.63, 75.94), controlPoint1: CGPointMake(74.4, 75.82), controlPoint2: CGPointMake(74.51, 75.9))
        bezierPath.addCurveToPoint(CGPointMake(75.37, 75.94), controlPoint1: CGPointMake(74.88, 76.02), controlPoint2: CGPointMake(75.12, 76.02))
        bezierPath.addCurveToPoint(CGPointMake(75.68, 75.71), controlPoint1: CGPointMake(75.49, 75.9), controlPoint2: CGPointMake(75.6, 75.82))
        bezierPath.addLineToPoint(CGPointMake(79.62, 71.96))
        bezierPath.addCurveToPoint(CGPointMake(79.65, 70.64), controlPoint1: CGPointMake(80.12, 71.53), controlPoint2: CGPointMake(80.13, 71.09))
        bezierPath.addCurveToPoint(CGPointMake(78.27, 70.67), controlPoint1: CGPointMake(79.18, 70.19), controlPoint2: CGPointMake(78.72, 70.2))
        bezierPath.addLineToPoint(CGPointMake(75.99, 72.78))
        bezierPath.addLineToPoint(CGPointMake(75.99, 49.22))
        bezierPath.addLineToPoint(CGPointMake(78.27, 51.33))
        bezierPath.closePath()
        bezierPath.miterLimit = 4;

        fillColor.setFill()
        bezierPath.fill()


        //// Bezier 2 Drawing
        let bezier2Path = UIBezierPath()
        bezier2Path.moveToPoint(CGPointMake(86.94, 164.63))
        bezier2Path.addCurveToPoint(CGPointMake(86.71, 164.32), controlPoint1: CGPointMake(86.9, 164.51), controlPoint2: CGPointMake(86.82, 164.4))
        bezier2Path.addLineToPoint(CGPointMake(82.96, 160.38))
        bezier2Path.addCurveToPoint(CGPointMake(81.64, 160.35), controlPoint1: CGPointMake(82.53, 159.88), controlPoint2: CGPointMake(82.09, 159.87))
        bezier2Path.addCurveToPoint(CGPointMake(81.67, 161.73), controlPoint1: CGPointMake(81.19, 160.82), controlPoint2: CGPointMake(81.2, 161.28))
        bezier2Path.addLineToPoint(CGPointMake(83.78, 164.01))
        bezier2Path.addLineToPoint(CGPointMake(60.22, 164.01))
        bezier2Path.addLineToPoint(CGPointMake(62.33, 161.73))
        bezier2Path.addCurveToPoint(CGPointMake(62.36, 160.35), controlPoint1: CGPointMake(62.8, 161.28), controlPoint2: CGPointMake(62.81, 160.82))
        bezier2Path.addCurveToPoint(CGPointMake(61.04, 160.38), controlPoint1: CGPointMake(61.91, 159.87), controlPoint2: CGPointMake(61.47, 159.88))
        bezier2Path.addLineToPoint(CGPointMake(57.29, 164.32))
        bezier2Path.addCurveToPoint(CGPointMake(57.06, 164.63), controlPoint1: CGPointMake(57.18, 164.4), controlPoint2: CGPointMake(57.1, 164.51))
        bezier2Path.addCurveToPoint(CGPointMake(57, 165), controlPoint1: CGPointMake(57.02, 164.75), controlPoint2: CGPointMake(57, 164.88))
        bezier2Path.addCurveToPoint(CGPointMake(57.06, 165.37), controlPoint1: CGPointMake(57, 165.12), controlPoint2: CGPointMake(57.02, 165.25))
        bezier2Path.addCurveToPoint(CGPointMake(57.29, 165.68), controlPoint1: CGPointMake(57.1, 165.49), controlPoint2: CGPointMake(57.18, 165.6))
        bezier2Path.addLineToPoint(CGPointMake(61.04, 169.62))
        bezier2Path.addCurveToPoint(CGPointMake(62.36, 169.65), controlPoint1: CGPointMake(61.47, 170.12), controlPoint2: CGPointMake(61.91, 170.13))
        bezier2Path.addCurveToPoint(CGPointMake(62.33, 168.27), controlPoint1: CGPointMake(62.81, 169.18), controlPoint2: CGPointMake(62.8, 168.72))
        bezier2Path.addLineToPoint(CGPointMake(60.22, 165.99))
        bezier2Path.addLineToPoint(CGPointMake(83.78, 165.99))
        bezier2Path.addLineToPoint(CGPointMake(81.67, 168.27))
        bezier2Path.addCurveToPoint(CGPointMake(81.64, 169.65), controlPoint1: CGPointMake(81.2, 168.72), controlPoint2: CGPointMake(81.19, 169.18))
        bezier2Path.addCurveToPoint(CGPointMake(82.96, 169.62), controlPoint1: CGPointMake(82.09, 170.13), controlPoint2: CGPointMake(82.53, 170.12))
        bezier2Path.addLineToPoint(CGPointMake(86.71, 165.68))
        bezier2Path.addCurveToPoint(CGPointMake(86.94, 165.37), controlPoint1: CGPointMake(86.82, 165.6), controlPoint2: CGPointMake(86.9, 165.49))
        bezier2Path.addCurveToPoint(CGPointMake(87, 165), controlPoint1: CGPointMake(86.98, 165.25), controlPoint2: CGPointMake(87, 165.12))
        bezier2Path.addCurveToPoint(CGPointMake(86.94, 164.63), controlPoint1: CGPointMake(87, 164.88), controlPoint2: CGPointMake(86.98, 164.75))
        bezier2Path.closePath()
        bezier2Path.miterLimit = 4;

        fillColor.setFill()
        bezier2Path.fill()
    }

    public class func drawLineSpacingSelected() {

        //// Bezier Drawing
        let bezierPath = UIBezierPath()
        bezierPath.moveToPoint(CGPointMake(18.27, 5.33))
        bezierPath.addCurveToPoint(CGPointMake(19.65, 5.36), controlPoint1: CGPointMake(18.72, 5.8), controlPoint2: CGPointMake(19.18, 5.81))
        bezierPath.addCurveToPoint(CGPointMake(19.62, 4.04), controlPoint1: CGPointMake(20.13, 4.91), controlPoint2: CGPointMake(20.12, 4.47))
        bezierPath.addLineToPoint(CGPointMake(15.68, 0.29))
        bezierPath.addCurveToPoint(CGPointMake(15.37, 0.06), controlPoint1: CGPointMake(15.6, 0.18), controlPoint2: CGPointMake(15.49, 0.1))
        bezierPath.addCurveToPoint(CGPointMake(14.63, 0.06), controlPoint1: CGPointMake(15.12, -0.02), controlPoint2: CGPointMake(14.88, -0.02))
        bezierPath.addCurveToPoint(CGPointMake(14.32, 0.29), controlPoint1: CGPointMake(14.51, 0.1), controlPoint2: CGPointMake(14.4, 0.18))
        bezierPath.addLineToPoint(CGPointMake(10.38, 4.04))
        bezierPath.addCurveToPoint(CGPointMake(10.35, 5.36), controlPoint1: CGPointMake(9.88, 4.47), controlPoint2: CGPointMake(9.87, 4.91))
        bezierPath.addCurveToPoint(CGPointMake(11.73, 5.33), controlPoint1: CGPointMake(10.82, 5.81), controlPoint2: CGPointMake(11.28, 5.8))
        bezierPath.addLineToPoint(CGPointMake(14.01, 3.22))
        bezierPath.addLineToPoint(CGPointMake(14.01, 26.78))
        bezierPath.addLineToPoint(CGPointMake(11.73, 24.67))
        bezierPath.addCurveToPoint(CGPointMake(10.35, 24.64), controlPoint1: CGPointMake(11.28, 24.2), controlPoint2: CGPointMake(10.82, 24.19))
        bezierPath.addCurveToPoint(CGPointMake(10.38, 25.96), controlPoint1: CGPointMake(9.87, 25.09), controlPoint2: CGPointMake(9.88, 25.53))
        bezierPath.addLineToPoint(CGPointMake(14.32, 29.71))
        bezierPath.addCurveToPoint(CGPointMake(14.63, 29.94), controlPoint1: CGPointMake(14.4, 29.82), controlPoint2: CGPointMake(14.51, 29.9))
        bezierPath.addCurveToPoint(CGPointMake(15.37, 29.94), controlPoint1: CGPointMake(14.88, 30.02), controlPoint2: CGPointMake(15.12, 30.02))
        bezierPath.addCurveToPoint(CGPointMake(15.68, 29.71), controlPoint1: CGPointMake(15.49, 29.9), controlPoint2: CGPointMake(15.6, 29.82))
        bezierPath.addLineToPoint(CGPointMake(19.62, 25.96))
        bezierPath.addCurveToPoint(CGPointMake(19.65, 24.64), controlPoint1: CGPointMake(20.12, 25.53), controlPoint2: CGPointMake(20.13, 25.09))
        bezierPath.addCurveToPoint(CGPointMake(18.27, 24.67), controlPoint1: CGPointMake(19.18, 24.19), controlPoint2: CGPointMake(18.72, 24.2))
        bezierPath.addLineToPoint(CGPointMake(15.99, 26.78))
        bezierPath.addLineToPoint(CGPointMake(15.99, 3.22))
        bezierPath.addLineToPoint(CGPointMake(18.27, 5.33))
        bezierPath.closePath()
        bezierPath.miterLimit = 4;

        CTAStyleKit.selectedColor.setFill()
        bezierPath.fill()
    }

    public class func drawTextSpacingSelected() {

        //// Bezier 2 Drawing
        let bezier2Path = UIBezierPath()
        bezier2Path.moveToPoint(CGPointMake(29.94, 14.63))
        bezier2Path.addCurveToPoint(CGPointMake(29.71, 14.32), controlPoint1: CGPointMake(29.9, 14.51), controlPoint2: CGPointMake(29.82, 14.4))
        bezier2Path.addLineToPoint(CGPointMake(25.96, 10.38))
        bezier2Path.addCurveToPoint(CGPointMake(24.64, 10.35), controlPoint1: CGPointMake(25.53, 9.88), controlPoint2: CGPointMake(25.09, 9.87))
        bezier2Path.addCurveToPoint(CGPointMake(24.67, 11.73), controlPoint1: CGPointMake(24.19, 10.82), controlPoint2: CGPointMake(24.2, 11.28))
        bezier2Path.addLineToPoint(CGPointMake(26.78, 14.01))
        bezier2Path.addLineToPoint(CGPointMake(3.22, 14.01))
        bezier2Path.addLineToPoint(CGPointMake(5.33, 11.73))
        bezier2Path.addCurveToPoint(CGPointMake(5.36, 10.35), controlPoint1: CGPointMake(5.8, 11.28), controlPoint2: CGPointMake(5.81, 10.82))
        bezier2Path.addCurveToPoint(CGPointMake(4.04, 10.38), controlPoint1: CGPointMake(4.91, 9.87), controlPoint2: CGPointMake(4.47, 9.88))
        bezier2Path.addLineToPoint(CGPointMake(0.29, 14.32))
        bezier2Path.addCurveToPoint(CGPointMake(0.06, 14.63), controlPoint1: CGPointMake(0.18, 14.4), controlPoint2: CGPointMake(0.1, 14.51))
        bezier2Path.addCurveToPoint(CGPointMake(0, 15), controlPoint1: CGPointMake(0.02, 14.75), controlPoint2: CGPointMake(0, 14.88))
        bezier2Path.addCurveToPoint(CGPointMake(0.06, 15.37), controlPoint1: CGPointMake(0, 15.12), controlPoint2: CGPointMake(0.02, 15.25))
        bezier2Path.addCurveToPoint(CGPointMake(0.29, 15.68), controlPoint1: CGPointMake(0.1, 15.49), controlPoint2: CGPointMake(0.18, 15.6))
        bezier2Path.addLineToPoint(CGPointMake(4.04, 19.62))
        bezier2Path.addCurveToPoint(CGPointMake(5.36, 19.65), controlPoint1: CGPointMake(4.47, 20.12), controlPoint2: CGPointMake(4.91, 20.13))
        bezier2Path.addCurveToPoint(CGPointMake(5.33, 18.27), controlPoint1: CGPointMake(5.81, 19.18), controlPoint2: CGPointMake(5.8, 18.72))
        bezier2Path.addLineToPoint(CGPointMake(3.22, 15.99))
        bezier2Path.addLineToPoint(CGPointMake(26.78, 15.99))
        bezier2Path.addLineToPoint(CGPointMake(24.67, 18.27))
        bezier2Path.addCurveToPoint(CGPointMake(24.64, 19.65), controlPoint1: CGPointMake(24.2, 18.72), controlPoint2: CGPointMake(24.19, 19.18))
        bezier2Path.addCurveToPoint(CGPointMake(25.96, 19.62), controlPoint1: CGPointMake(25.09, 20.13), controlPoint2: CGPointMake(25.53, 20.12))
        bezier2Path.addLineToPoint(CGPointMake(29.71, 15.68))
        bezier2Path.addCurveToPoint(CGPointMake(29.94, 15.37), controlPoint1: CGPointMake(29.82, 15.6), controlPoint2: CGPointMake(29.9, 15.49))
        bezier2Path.addCurveToPoint(CGPointMake(30, 15), controlPoint1: CGPointMake(29.98, 15.25), controlPoint2: CGPointMake(30, 15.12))
        bezier2Path.addCurveToPoint(CGPointMake(29.94, 14.63), controlPoint1: CGPointMake(30, 14.88), controlPoint2: CGPointMake(29.98, 14.75))
        bezier2Path.closePath()
        bezier2Path.miterLimit = 4;

        CTAStyleKit.selectedColor.setFill()
        bezier2Path.fill()
    }

    public class func drawTextSpacingNormal() {

        //// Bezier 2 Drawing
        let bezier2Path = UIBezierPath()
        bezier2Path.moveToPoint(CGPointMake(29.94, 14.63))
        bezier2Path.addCurveToPoint(CGPointMake(29.71, 14.32), controlPoint1: CGPointMake(29.9, 14.51), controlPoint2: CGPointMake(29.82, 14.4))
        bezier2Path.addLineToPoint(CGPointMake(25.96, 10.38))
        bezier2Path.addCurveToPoint(CGPointMake(24.64, 10.35), controlPoint1: CGPointMake(25.53, 9.88), controlPoint2: CGPointMake(25.09, 9.87))
        bezier2Path.addCurveToPoint(CGPointMake(24.67, 11.73), controlPoint1: CGPointMake(24.19, 10.82), controlPoint2: CGPointMake(24.2, 11.28))
        bezier2Path.addLineToPoint(CGPointMake(26.78, 14.01))
        bezier2Path.addLineToPoint(CGPointMake(3.22, 14.01))
        bezier2Path.addLineToPoint(CGPointMake(5.33, 11.73))
        bezier2Path.addCurveToPoint(CGPointMake(5.36, 10.35), controlPoint1: CGPointMake(5.8, 11.28), controlPoint2: CGPointMake(5.81, 10.82))
        bezier2Path.addCurveToPoint(CGPointMake(4.04, 10.38), controlPoint1: CGPointMake(4.91, 9.87), controlPoint2: CGPointMake(4.47, 9.88))
        bezier2Path.addLineToPoint(CGPointMake(0.29, 14.32))
        bezier2Path.addCurveToPoint(CGPointMake(0.06, 14.63), controlPoint1: CGPointMake(0.18, 14.4), controlPoint2: CGPointMake(0.1, 14.51))
        bezier2Path.addCurveToPoint(CGPointMake(0, 15), controlPoint1: CGPointMake(0.02, 14.75), controlPoint2: CGPointMake(0, 14.88))
        bezier2Path.addCurveToPoint(CGPointMake(0.06, 15.37), controlPoint1: CGPointMake(0, 15.12), controlPoint2: CGPointMake(0.02, 15.25))
        bezier2Path.addCurveToPoint(CGPointMake(0.29, 15.68), controlPoint1: CGPointMake(0.1, 15.49), controlPoint2: CGPointMake(0.18, 15.6))
        bezier2Path.addLineToPoint(CGPointMake(4.04, 19.62))
        bezier2Path.addCurveToPoint(CGPointMake(5.36, 19.65), controlPoint1: CGPointMake(4.47, 20.12), controlPoint2: CGPointMake(4.91, 20.13))
        bezier2Path.addCurveToPoint(CGPointMake(5.33, 18.27), controlPoint1: CGPointMake(5.81, 19.18), controlPoint2: CGPointMake(5.8, 18.72))
        bezier2Path.addLineToPoint(CGPointMake(3.22, 15.99))
        bezier2Path.addLineToPoint(CGPointMake(26.78, 15.99))
        bezier2Path.addLineToPoint(CGPointMake(24.67, 18.27))
        bezier2Path.addCurveToPoint(CGPointMake(24.64, 19.65), controlPoint1: CGPointMake(24.2, 18.72), controlPoint2: CGPointMake(24.19, 19.18))
        bezier2Path.addCurveToPoint(CGPointMake(25.96, 19.62), controlPoint1: CGPointMake(25.09, 20.13), controlPoint2: CGPointMake(25.53, 20.12))
        bezier2Path.addLineToPoint(CGPointMake(29.71, 15.68))
        bezier2Path.addCurveToPoint(CGPointMake(29.94, 15.37), controlPoint1: CGPointMake(29.82, 15.6), controlPoint2: CGPointMake(29.9, 15.49))
        bezier2Path.addCurveToPoint(CGPointMake(30, 15), controlPoint1: CGPointMake(29.98, 15.25), controlPoint2: CGPointMake(30, 15.12))
        bezier2Path.addCurveToPoint(CGPointMake(29.94, 14.63), controlPoint1: CGPointMake(30, 14.88), controlPoint2: CGPointMake(29.98, 14.75))
        bezier2Path.closePath()
        bezier2Path.miterLimit = 4;

        CTAStyleKit.normalColor.setFill()
        bezier2Path.fill()
    }

    //// Generated Images

    public class var imageOfAlignmentRightSelected: UIImage {
        if Cache.imageOfAlignmentRightSelected != nil {
            return Cache.imageOfAlignmentRightSelected!
        }

        UIGraphicsBeginImageContextWithOptions(CGSizeMake(30, 30), false, 0)
            CTAStyleKit.drawAlignmentRightSelected()

        Cache.imageOfAlignmentRightSelected = UIGraphicsGetImageFromCurrentImageContext()
        UIGraphicsEndImageContext()

        return Cache.imageOfAlignmentRightSelected!
    }

    public class var imageOfAlignmentRightNormal: UIImage {
        if Cache.imageOfAlignmentRightNormal != nil {
            return Cache.imageOfAlignmentRightNormal!
        }

        UIGraphicsBeginImageContextWithOptions(CGSizeMake(30, 30), false, 0)
            CTAStyleKit.drawAlignmentRightNormal()

        Cache.imageOfAlignmentRightNormal = UIGraphicsGetImageFromCurrentImageContext()
        UIGraphicsEndImageContext()

        return Cache.imageOfAlignmentRightNormal!
    }

    public class var imageOfAlignmentLeftSelected: UIImage {
        if Cache.imageOfAlignmentLeftSelected != nil {
            return Cache.imageOfAlignmentLeftSelected!
        }

        UIGraphicsBeginImageContextWithOptions(CGSizeMake(30, 30), false, 0)
            CTAStyleKit.drawAlignmentLeftSelected()

        Cache.imageOfAlignmentLeftSelected = UIGraphicsGetImageFromCurrentImageContext()
        UIGraphicsEndImageContext()

        return Cache.imageOfAlignmentLeftSelected!
    }

    public class var imageOfAlignmentLeftNormal: UIImage {
        if Cache.imageOfAlignmentLeftNormal != nil {
            return Cache.imageOfAlignmentLeftNormal!
        }

        UIGraphicsBeginImageContextWithOptions(CGSizeMake(30, 30), false, 0)
            CTAStyleKit.drawAlignmentLeftNormal()

        Cache.imageOfAlignmentLeftNormal = UIGraphicsGetImageFromCurrentImageContext()
        UIGraphicsEndImageContext()

        return Cache.imageOfAlignmentLeftNormal!
    }

    public class var imageOfAlignmentCenterSelected: UIImage {
        if Cache.imageOfAlignmentCenterSelected != nil {
            return Cache.imageOfAlignmentCenterSelected!
        }

        UIGraphicsBeginImageContextWithOptions(CGSizeMake(30, 30), false, 0)
            CTAStyleKit.drawAlignmentCenterSelected()

        Cache.imageOfAlignmentCenterSelected = UIGraphicsGetImageFromCurrentImageContext()
        UIGraphicsEndImageContext()

        return Cache.imageOfAlignmentCenterSelected!
    }

    public class var imageOfAlignmentCenterNormal: UIImage {
        if Cache.imageOfAlignmentCenterNormal != nil {
            return Cache.imageOfAlignmentCenterNormal!
        }

        UIGraphicsBeginImageContextWithOptions(CGSizeMake(30, 30), false, 0)
            CTAStyleKit.drawAlignmentCenterNormal()

        Cache.imageOfAlignmentCenterNormal = UIGraphicsGetImageFromCurrentImageContext()
        UIGraphicsEndImageContext()

        return Cache.imageOfAlignmentCenterNormal!
    }

    public class var imageOfAlignmentJustNormal: UIImage {
        if Cache.imageOfAlignmentJustNormal != nil {
            return Cache.imageOfAlignmentJustNormal!
        }

        UIGraphicsBeginImageContextWithOptions(CGSizeMake(30, 30), false, 0)
            CTAStyleKit.drawAlignmentJustNormal()

        Cache.imageOfAlignmentJustNormal = UIGraphicsGetImageFromCurrentImageContext()
        UIGraphicsEndImageContext()

        return Cache.imageOfAlignmentJustNormal!
    }

    public class var imageOfAlignmentJustSelected: UIImage {
        if Cache.imageOfAlignmentJustSelected != nil {
            return Cache.imageOfAlignmentJustSelected!
        }

        UIGraphicsBeginImageContextWithOptions(CGSizeMake(30, 30), false, 0)
            CTAStyleKit.drawAlignmentJustSelected()

        Cache.imageOfAlignmentJustSelected = UIGraphicsGetImageFromCurrentImageContext()
        UIGraphicsEndImageContext()

        return Cache.imageOfAlignmentJustSelected!
    }

    public class var imageOfLineSpacingNormal: UIImage {
        if Cache.imageOfLineSpacingNormal != nil {
            return Cache.imageOfLineSpacingNormal!
        }

        UIGraphicsBeginImageContextWithOptions(CGSizeMake(30, 30), false, 0)
            CTAStyleKit.drawLineSpacingNormal()

        Cache.imageOfLineSpacingNormal = UIGraphicsGetImageFromCurrentImageContext()
        UIGraphicsEndImageContext()

        return Cache.imageOfLineSpacingNormal!
    }

    public class var imageOfLineSpacingSelected: UIImage {
        if Cache.imageOfLineSpacingSelected != nil {
            return Cache.imageOfLineSpacingSelected!
        }

        UIGraphicsBeginImageContextWithOptions(CGSizeMake(30, 30), false, 0)
            CTAStyleKit.drawLineSpacingSelected()

        Cache.imageOfLineSpacingSelected = UIGraphicsGetImageFromCurrentImageContext()
        UIGraphicsEndImageContext()

        return Cache.imageOfLineSpacingSelected!
    }

    public class var imageOfTextSpacingSelected: UIImage {
        if Cache.imageOfTextSpacingSelected != nil {
            return Cache.imageOfTextSpacingSelected!
        }

        UIGraphicsBeginImageContextWithOptions(CGSizeMake(30, 30), false, 0)
            CTAStyleKit.drawTextSpacingSelected()

        Cache.imageOfTextSpacingSelected = UIGraphicsGetImageFromCurrentImageContext()
        UIGraphicsEndImageContext()

        return Cache.imageOfTextSpacingSelected!
    }

    public class var imageOfTextSpacingNormal: UIImage {
        if Cache.imageOfTextSpacingNormal != nil {
            return Cache.imageOfTextSpacingNormal!
        }

        UIGraphicsBeginImageContextWithOptions(CGSizeMake(30, 30), false, 0)
            CTAStyleKit.drawTextSpacingNormal()

        Cache.imageOfTextSpacingNormal = UIGraphicsGetImageFromCurrentImageContext()
        UIGraphicsEndImageContext()

        return Cache.imageOfTextSpacingNormal!
    }

    //// Customization Infrastructure

    @IBOutlet var alignmentRightSelectedTargets: [AnyObject]! {
        get { return Cache.alignmentRightSelectedTargets }
        set {
            Cache.alignmentRightSelectedTargets = newValue
            for target: AnyObject in newValue {
                target.performSelector("setImage:", withObject: CTAStyleKit.imageOfAlignmentRightSelected)
            }
        }
    }

    @IBOutlet var alignmentRightNormalTargets: [AnyObject]! {
        get { return Cache.alignmentRightNormalTargets }
        set {
            Cache.alignmentRightNormalTargets = newValue
            for target: AnyObject in newValue {
                target.performSelector("setImage:", withObject: CTAStyleKit.imageOfAlignmentRightNormal)
            }
        }
    }

    @IBOutlet var alignmentLeftSelectedTargets: [AnyObject]! {
        get { return Cache.alignmentLeftSelectedTargets }
        set {
            Cache.alignmentLeftSelectedTargets = newValue
            for target: AnyObject in newValue {
                target.performSelector("setImage:", withObject: CTAStyleKit.imageOfAlignmentLeftSelected)
            }
        }
    }

    @IBOutlet var alignmentLeftNormalTargets: [AnyObject]! {
        get { return Cache.alignmentLeftNormalTargets }
        set {
            Cache.alignmentLeftNormalTargets = newValue
            for target: AnyObject in newValue {
                target.performSelector("setImage:", withObject: CTAStyleKit.imageOfAlignmentLeftNormal)
            }
        }
    }

    @IBOutlet var alignmentCenterSelectedTargets: [AnyObject]! {
        get { return Cache.alignmentCenterSelectedTargets }
        set {
            Cache.alignmentCenterSelectedTargets = newValue
            for target: AnyObject in newValue {
                target.performSelector("setImage:", withObject: CTAStyleKit.imageOfAlignmentCenterSelected)
            }
        }
    }

    @IBOutlet var alignmentCenterNormalTargets: [AnyObject]! {
        get { return Cache.alignmentCenterNormalTargets }
        set {
            Cache.alignmentCenterNormalTargets = newValue
            for target: AnyObject in newValue {
                target.performSelector("setImage:", withObject: CTAStyleKit.imageOfAlignmentCenterNormal)
            }
        }
    }

    @IBOutlet var alignmentJustNormalTargets: [AnyObject]! {
        get { return Cache.alignmentJustNormalTargets }
        set {
            Cache.alignmentJustNormalTargets = newValue
            for target: AnyObject in newValue {
                target.performSelector("setImage:", withObject: CTAStyleKit.imageOfAlignmentJustNormal)
            }
        }
    }

    @IBOutlet var alignmentJustSelectedTargets: [AnyObject]! {
        get { return Cache.alignmentJustSelectedTargets }
        set {
            Cache.alignmentJustSelectedTargets = newValue
            for target: AnyObject in newValue {
                target.performSelector("setImage:", withObject: CTAStyleKit.imageOfAlignmentJustSelected)
            }
        }
    }

    @IBOutlet var lineSpacingNormalTargets: [AnyObject]! {
        get { return Cache.lineSpacingNormalTargets }
        set {
            Cache.lineSpacingNormalTargets = newValue
            for target: AnyObject in newValue {
                target.performSelector("setImage:", withObject: CTAStyleKit.imageOfLineSpacingNormal)
            }
        }
    }

    @IBOutlet var lineSpacingSelectedTargets: [AnyObject]! {
        get { return Cache.lineSpacingSelectedTargets }
        set {
            Cache.lineSpacingSelectedTargets = newValue
            for target: AnyObject in newValue {
                target.performSelector("setImage:", withObject: CTAStyleKit.imageOfLineSpacingSelected)
            }
        }
    }

    @IBOutlet var textSpacingSelectedTargets: [AnyObject]! {
        get { return Cache.textSpacingSelectedTargets }
        set {
            Cache.textSpacingSelectedTargets = newValue
            for target: AnyObject in newValue {
                target.performSelector("setImage:", withObject: CTAStyleKit.imageOfTextSpacingSelected)
            }
        }
    }

    @IBOutlet var textSpacingNormalTargets: [AnyObject]! {
        get { return Cache.textSpacingNormalTargets }
        set {
            Cache.textSpacingNormalTargets = newValue
            for target: AnyObject in newValue {
                target.performSelector("setImage:", withObject: CTAStyleKit.imageOfTextSpacingNormal)
            }
        }
    }

}
