# Uncomment this line to define a global platform for your project
platform :ios, '8.0'
# Uncomment this line if you're using Swift
use_frameworks!

target 'CuriosTextApp' do
pod 'Alamofire', '~> 3.1.3'
pod 'Locksmith'
pod 'SwiftyJSON', '~> 2.3.2'
pod "Qiniu", '~> 7.0'
pod 'Kingfisher', '~> 1.8.5'
pod 'MJRefresh', '~> 3.0.7'
pod 'pop', '~> 1.0.8'
pod 'MonkeyKing', '~> 0.9'
pod 'KeyboardMan', '~> 0.5.2'
pod 'PromiseKit', '~> 3.0.2'
pod 'SVProgressHUD', '~> 2.0-beta8'
end

target 'CuriosTextAppTests' do

end

target 'CuriosTextAppUITests' do

end

